name: Continuous Integration

on:
  push:

jobs:
  ci-linux:
    permissions:
      contents: read
      pages: write
      id-token: write
    name: CI Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: typst-community/setup-typst@v4
      - uses: jim60105/action-install-google-fonts@v2
        with:
          fonts: "Noto Sans"
      - run: ./build.sh
        shell: bash
      - run: ./build.sh svg
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Generated PDF files
          path: |
            dist/*.pdf
      - name: Upload pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist/
      - name: Deploy to GitHub Pages
        if: ${{ github.ref == 'refs/heads/main' }}
        id: deployment
        uses: actions/deploy-pages@v4
